import Head from "next/head";
import Link from "next/link"
import { Button } from "flowbite-react";
import Image from "next/image";
import { Carousel, Accordion } from "flowbite-react";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      {
        <div className="h-56 sm:h-64 xl:h-80 2xl:h-96">
          <Carousel slide={false}>
            <img src="sample.jpeg" alt="..." />
            <img
              src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
              alt="..."
            />
            <img
              src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
              alt="..."
            />
            <img
              src="https://flowbite.com/docs/images/carousel/carousel-4.svg"
              alt="..."
            />
            <img
              src="https://flowbite.com/docs/images/carousel/carousel-5.svg"
              alt="..."
            />
          </Carousel>
        </div>
      }

      <div
        className={
          "flex flex-col items-center bg-slate-100 text-blue-900 min-h-screen"
        }
      >
        {
          <Head>
            <title>NFT-Garage</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script src="../path/to/flowbite/dist/flowbite.js"></script>;
          </Head>
        }
        <h2 className={"text-6xl font-bold my-12 mt-8"}>
          あなただけのNFTガレージ
        </h2>

        {/* 説明文ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー */}
        <Accordion alwaysOpen={true}>
          <Accordion.Panel>
            <Accordion.Title>どんなプロダクトか？</Accordion.Title>
            <Accordion.Content>
              <p className="mb-2 text-gray-500 dark:text-gray-400">
                ウォレットに接続することで、自分の保有しているNFTが表示されます。
                自分は今どんなNFTを保有しているかわからない、という課題を解決してくれるアプリケーションです。
              </p>
              {/* <p className="text-gray-500 dark:text-gray-400">
                  Check out this guide to learn how to{" "}
                  <a
                    href="https://flowbite.com/docs/getting-started/introduction/"
                    className="text-blue-600 hover:underline dark:text-blue-500"
                  >
                    get started
                  </a>{" "}
                  and start developing websites even faster with components on
                  top of Tailwind CSS.
                </p> */}
            </Accordion.Content>
          </Accordion.Panel>
          <Accordion.Panel>
            <Accordion.Title>ウォレット接続に関して</Accordion.Title>
            <Accordion.Content>
              <p className="mb-2 text-gray-500 dark:text-gray-400">
                現在はアルファ版の前のテストアプリのため、Rinkebyのテストネットにデプロイしています。
              </p>
              <p>今後はさまざまなチェーンに対応させる予定です。</p>
              {/* <p className="text-gray-500 dark:text-gray-400">
                  Check out the{" "}
                  <a
                    href="https://flowbite.com/figma/"
                    className="text-blue-600 hover:underline dark:text-blue-500"
                  >
                    Figma design system
                  </a>{" "}
                  based on the utility classes from Tailwind CSS and components
                  from Flowbite.
                </p> */}
            </Accordion.Content>
          </Accordion.Panel>
          <Accordion.Panel>
            <Accordion.Title>今後について</Accordion.Title>
            <Accordion.Content>
              <p className="mb-2 text-gray-500 dark:text-gray-400">
                現在はロードマップを含むドキュメントを整備中です。
              </p>
              <p className="mb-2 text-gray-500 dark:text-gray-400">
                いずれは、ソーシャル機能を持たせて、いろんな人のNFTコレクションを見に行くことができたり、そこにトークンを投げ銭したりなど、さまざまな機能を拡張していく予定です。
              </p>
              <p className="mb-2 text-gray-500 dark:text-gray-400">
                開発陣は一人です。ある程度の形になれば、DAOを作り、ステークホルダーみんなで楽しいプロダクトを作っていきましょう！
              </p>
              <ul className="list-disc pl-5 text-gray-500 dark:text-gray-400">
                <li>
                  <a
                    href=""
                    className="text-blue-600 hover:underline dark:text-blue-500"
                  >
                    ドキュメント（準備中）
                  </a>
                </li>
                <li>
                  <a
                    href="/contact"
                    rel="nofollow"
                    className="text-blue-600 hover:underline dark:text-blue-500"
                  >
                    ファウンダー
                  </a>
                </li>
              </ul>
            </Accordion.Content>
          </Accordion.Panel>
        </Accordion>
        {/* ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー */}

        {/* ボタンーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー */}
        <div className="flex flex-wrap gap-3 py-10">
          <Link href="/dashboard">
            <Button size="xl" gradientDuoTone="purpleToPink">
              Go App
            </Button>
          </Link>
        </div>
      </div>
    </Layout>
  );
}
